var num1 = -30;
var num2 = 100;
var num3 = 2;
var num4 = -300;
var string1 = "me";
var string2 = "pie";
var string3 = "apple";
var boolean1 = true;
var boolean2 = false;
var undefined1 = undefined;
console.log("The First Sting is " + num1);
console.log("The First Sting is " + num2);
console.log("The First Sting is " + num3);
console.log("The First Sting is " + num4);
console.log("The First Sting is " + string1);
console.log("The First Sting is " + string2);
console.log("The First Sting is " + string3);
console.log("The First Sting is " + boolean1);
console.log("The First Sting is " + boolean2);
console.log("The First Sting is " + undefined1);